### ISSUE TITLE
Markbot/index.html error

### ISSUE THREAD

**Issue by Amy-Stalter** [Amy-Stalter/css-validation-fixes#1]
@thomasjbradley
Markbot will not let me put the page online. I have done and pushed my commits, and I have properly named the files.

Thank you.

**Comment by thomasjbradley** [comment]
https://github.com/Amy-Stalter/css-validation-fixes

Check out this page. Is there something wrong with the index file?

**Comment by Amy-Stalter** [comment]
@thomasjbradley I went into github and directly changed the name. Thank you.
